package com.justedlev.service.phonenumber.api;

public enum Code {
    OK,
    AIRLINE_NOT_EXISTS, AIRLINE_ALREADY_EXISTS,
    AIRCRAFT_NOT_EXISTS, AIRCRAFT_ALREADY_EXISTS,
    AIRCRAFT_IN_AIRLINE_ALREADY_EXISTS,
    AIRLINE_AND_DESTINATION_NAMES_MUST_BE_DIFFERENT,
    AIRLINE_NOT_HAVE_SUCH_AIRCRAFT,
    AIRLINE_DESTINATION_ALREADY_EXISTS, AIRLINE_DESTINATION_NOT_ADDED,
    DESTINATION_NOT_EXISTS, DESTINATION_ALREADY_EXISTS,
    AIRCRAFT_IN_AIRLINE_NOT_FOUND
}
